server:
  port: 8080

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  data:
    redis:
      host: redis
      port: 6379
  
  datasource:
    url: jdbc:postgresql://postgres:5432/acsdb
    username: acsuser
    password: acspass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
