server:
  port: 8080

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  data:
    redis:
      host: redis
      port: 6379
      timeout: 3000
      connect-timeout: 3000
  
  datasource:
    url: jdbc:postgresql://postgres:5432/acsdb
    username: acsuser
    password: acspass
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: -1 # ← wait for DB indefinitely

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET:bXlzZWNyZXRrZXltYWtlc3VyZXRvaGF2ZXZhbGlkaW50ZXJ2YWw=}
