server:
  port: 8080
  servlet:
    context-path: /sms

spring:
  application:
    name: sms-service
  kafka:
    bootstrap-servers: kafka:9092


sms:
  gateway-url: http://192.168.2.38:8080/send-sms
  token: your_secure_token