server:
  port: 8080

spring:
  application:
    name: report-service

auth-service:
  url: http://auth-service:8080

jwt:
  secret: ${JWT_SECRET:bXlzZWNyZXRrZXltYWtlc3VyZXRvaGF2ZXZhbGlkaW50ZXJ2YWw=}


#   security:
#     oauth2:
#       resourceserver:
#         jwt:
          # We decode using shared symmetric key
          # No need for issuer or JWK if you use `JwtDecoder` bean

