server:
  port: 8080

spring:
  application:
    name: report-service

#   security:
#     oauth2:
#       resourceserver:
#         jwt:
          # We decode using shared symmetric key
          # No need for issuer or JWK if you use `JwtDecoder` bean

