server:
  port: 8080
  servlet:
    context-path: /users

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres:5432/acsdb
    username: acsuser
    password: acspass
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: -1 # ← wait for DB indefinitely

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # Will be overridden by custom decoder bean
          jwk-set-uri: ignored

auth-service:
  url: http://auth-service:8080

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET:bXlzZWNyZXRrZXltYWtlc3VyZXRvaGF2ZXZhbGlkaW50ZXJ2YWw=}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  default-produces-media-type: application/json
